// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package org.learn.grpc.api;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuangqi_grpc_api_RPCDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chuangqi_grpc_api_RPCDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuangqi_grpc_api_RPCDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chuangqi_grpc_api_RPCDateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuangqi_grpc_api_RPCDateResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chuangqi_grpc_api_RPCDateResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021DataService.proto\022\025com.chuangqi.grpc.a" +
      "pi\"\"\n\016RPCDateRequest\022\020\n\010userName\030\001 \001(\t\"%" +
      "\n\017RPCDateResponse\022\022\n\nserverDate\030\001 \001(\t\"V\n" +
      "\023RPCDateResponseList\022?\n\017rPCDateResponse\030" +
      "\001 \003(\0132&.com.chuangqi.grpc.api.RPCDateRes" +
      "ponse2\235\003\n\016RPCDateService\022Z\n\007getDate\022%.co" +
      "m.chuangqi.grpc.api.RPCDateRequest\032&.com" +
      ".chuangqi.grpc.api.RPCDateResponse\"\000\022b\n\r" +
      "getDateStream\022%.com.chuangqi.grpc.api.RP" +
      "CDateRequest\032&.com.chuangqi.grpc.api.RPC",
      "DateResponse\"\0000\001\022c\n\014doubleStream\022%.com.c" +
      "huangqi.grpc.api.RPCDateRequest\032&.com.ch" +
      "uangqi.grpc.api.RPCDateResponse\"\000(\0010\001\022f\n" +
      "\013stream2Data\022%.com.chuangqi.grpc.api.RPC" +
      "DateRequest\032*.com.chuangqi.grpc.api.RPCD" +
      "ateResponseList\"\000(\0010\001B,\n\025com.chuangqi.gr" +
      "pc.apiB\021RPCDateServiceApiP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chuangqi_grpc_api_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuangqi_grpc_api_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chuangqi_grpc_api_RPCDateRequest_descriptor,
        new String[] { "UserName", });
    internal_static_com_chuangqi_grpc_api_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chuangqi_grpc_api_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chuangqi_grpc_api_RPCDateResponse_descriptor,
        new String[] { "ServerDate", });
    internal_static_com_chuangqi_grpc_api_RPCDateResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chuangqi_grpc_api_RPCDateResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chuangqi_grpc_api_RPCDateResponseList_descriptor,
        new String[] { "RPCDateResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
