// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package org.learn.grpc.api;

/**
 * <pre>
 * 定义相应内容
 * </pre>
 *
 * Protobuf type {@code com.chuangqi.grpc.api.RPCDateResponseList}
 */
public  final class RPCDateResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.chuangqi.grpc.api.RPCDateResponseList)
    RPCDateResponseListOrBuilder {
  // Use RPCDateResponseList.newBuilder() to construct.
  private RPCDateResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RPCDateResponseList() {
    rPCDateResponse_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RPCDateResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              rPCDateResponse_ = new java.util.ArrayList<RPCDateResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            rPCDateResponse_.add(
                input.readMessage(RPCDateResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        rPCDateResponse_ = java.util.Collections.unmodifiableList(rPCDateResponse_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RPCDateServiceApi.internal_static_com_chuangqi_grpc_api_RPCDateResponseList_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RPCDateServiceApi.internal_static_com_chuangqi_grpc_api_RPCDateResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RPCDateResponseList.class, Builder.class);
  }

  public static final int RPCDATERESPONSE_FIELD_NUMBER = 1;
  private java.util.List<RPCDateResponse> rPCDateResponse_;
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  public java.util.List<RPCDateResponse> getRPCDateResponseList() {
    return rPCDateResponse_;
  }
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  public java.util.List<? extends RPCDateResponseOrBuilder>
      getRPCDateResponseOrBuilderList() {
    return rPCDateResponse_;
  }
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  public int getRPCDateResponseCount() {
    return rPCDateResponse_.size();
  }
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  public RPCDateResponse getRPCDateResponse(int index) {
    return rPCDateResponse_.get(index);
  }
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  public RPCDateResponseOrBuilder getRPCDateResponseOrBuilder(
      int index) {
    return rPCDateResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rPCDateResponse_.size(); i++) {
      output.writeMessage(1, rPCDateResponse_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rPCDateResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rPCDateResponse_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RPCDateResponseList)) {
      return super.equals(obj);
    }
    RPCDateResponseList other = (RPCDateResponseList) obj;

    boolean result = true;
    result = result && getRPCDateResponseList()
        .equals(other.getRPCDateResponseList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getRPCDateResponseCount() > 0) {
      hash = (37 * hash) + RPCDATERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getRPCDateResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RPCDateResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RPCDateResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RPCDateResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RPCDateResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RPCDateResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RPCDateResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RPCDateResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RPCDateResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RPCDateResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RPCDateResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RPCDateResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义相应内容
   * </pre>
   *
   * Protobuf type {@code com.chuangqi.grpc.api.RPCDateResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chuangqi.grpc.api.RPCDateResponseList)
      RPCDateResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RPCDateServiceApi.internal_static_com_chuangqi_grpc_api_RPCDateResponseList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RPCDateServiceApi.internal_static_com_chuangqi_grpc_api_RPCDateResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RPCDateResponseList.class, Builder.class);
    }

    // Construct using com.chuangqi.grpc.api.RPCDateResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRPCDateResponseFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (rPCDateResponseBuilder_ == null) {
        rPCDateResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rPCDateResponseBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RPCDateServiceApi.internal_static_com_chuangqi_grpc_api_RPCDateResponseList_descriptor;
    }

    public RPCDateResponseList getDefaultInstanceForType() {
      return RPCDateResponseList.getDefaultInstance();
    }

    public RPCDateResponseList build() {
      RPCDateResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RPCDateResponseList buildPartial() {
      RPCDateResponseList result = new RPCDateResponseList(this);
      int from_bitField0_ = bitField0_;
      if (rPCDateResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          rPCDateResponse_ = java.util.Collections.unmodifiableList(rPCDateResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rPCDateResponse_ = rPCDateResponse_;
      } else {
        result.rPCDateResponse_ = rPCDateResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RPCDateResponseList) {
        return mergeFrom((RPCDateResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RPCDateResponseList other) {
      if (other == RPCDateResponseList.getDefaultInstance()) return this;
      if (rPCDateResponseBuilder_ == null) {
        if (!other.rPCDateResponse_.isEmpty()) {
          if (rPCDateResponse_.isEmpty()) {
            rPCDateResponse_ = other.rPCDateResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRPCDateResponseIsMutable();
            rPCDateResponse_.addAll(other.rPCDateResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.rPCDateResponse_.isEmpty()) {
          if (rPCDateResponseBuilder_.isEmpty()) {
            rPCDateResponseBuilder_.dispose();
            rPCDateResponseBuilder_ = null;
            rPCDateResponse_ = other.rPCDateResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rPCDateResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRPCDateResponseFieldBuilder() : null;
          } else {
            rPCDateResponseBuilder_.addAllMessages(other.rPCDateResponse_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RPCDateResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RPCDateResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<RPCDateResponse> rPCDateResponse_ =
      java.util.Collections.emptyList();
    private void ensureRPCDateResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        rPCDateResponse_ = new java.util.ArrayList<RPCDateResponse>(rPCDateResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        RPCDateResponse, RPCDateResponse.Builder, RPCDateResponseOrBuilder> rPCDateResponseBuilder_;

    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public java.util.List<RPCDateResponse> getRPCDateResponseList() {
      if (rPCDateResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rPCDateResponse_);
      } else {
        return rPCDateResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public int getRPCDateResponseCount() {
      if (rPCDateResponseBuilder_ == null) {
        return rPCDateResponse_.size();
      } else {
        return rPCDateResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public RPCDateResponse getRPCDateResponse(int index) {
      if (rPCDateResponseBuilder_ == null) {
        return rPCDateResponse_.get(index);
      } else {
        return rPCDateResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder setRPCDateResponse(
        int index, RPCDateResponse value) {
      if (rPCDateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.set(index, value);
        onChanged();
      } else {
        rPCDateResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder setRPCDateResponse(
        int index, RPCDateResponse.Builder builderForValue) {
      if (rPCDateResponseBuilder_ == null) {
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        rPCDateResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder addRPCDateResponse(RPCDateResponse value) {
      if (rPCDateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.add(value);
        onChanged();
      } else {
        rPCDateResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder addRPCDateResponse(
        int index, RPCDateResponse value) {
      if (rPCDateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.add(index, value);
        onChanged();
      } else {
        rPCDateResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder addRPCDateResponse(
        RPCDateResponse.Builder builderForValue) {
      if (rPCDateResponseBuilder_ == null) {
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.add(builderForValue.build());
        onChanged();
      } else {
        rPCDateResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder addRPCDateResponse(
        int index, RPCDateResponse.Builder builderForValue) {
      if (rPCDateResponseBuilder_ == null) {
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        rPCDateResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder addAllRPCDateResponse(
        Iterable<? extends RPCDateResponse> values) {
      if (rPCDateResponseBuilder_ == null) {
        ensureRPCDateResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rPCDateResponse_);
        onChanged();
      } else {
        rPCDateResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder clearRPCDateResponse() {
      if (rPCDateResponseBuilder_ == null) {
        rPCDateResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rPCDateResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public Builder removeRPCDateResponse(int index) {
      if (rPCDateResponseBuilder_ == null) {
        ensureRPCDateResponseIsMutable();
        rPCDateResponse_.remove(index);
        onChanged();
      } else {
        rPCDateResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public RPCDateResponse.Builder getRPCDateResponseBuilder(
        int index) {
      return getRPCDateResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public RPCDateResponseOrBuilder getRPCDateResponseOrBuilder(
        int index) {
      if (rPCDateResponseBuilder_ == null) {
        return rPCDateResponse_.get(index);  } else {
        return rPCDateResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public java.util.List<? extends RPCDateResponseOrBuilder>
         getRPCDateResponseOrBuilderList() {
      if (rPCDateResponseBuilder_ != null) {
        return rPCDateResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rPCDateResponse_);
      }
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public RPCDateResponse.Builder addRPCDateResponseBuilder() {
      return getRPCDateResponseFieldBuilder().addBuilder(
          RPCDateResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public RPCDateResponse.Builder addRPCDateResponseBuilder(
        int index) {
      return getRPCDateResponseFieldBuilder().addBuilder(
          index, RPCDateResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
     */
    public java.util.List<RPCDateResponse.Builder>
         getRPCDateResponseBuilderList() {
      return getRPCDateResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        RPCDateResponse, RPCDateResponse.Builder, RPCDateResponseOrBuilder>
        getRPCDateResponseFieldBuilder() {
      if (rPCDateResponseBuilder_ == null) {
        rPCDateResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            RPCDateResponse, RPCDateResponse.Builder, RPCDateResponseOrBuilder>(
                rPCDateResponse_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        rPCDateResponse_ = null;
      }
      return rPCDateResponseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.chuangqi.grpc.api.RPCDateResponseList)
  }

  // @@protoc_insertion_point(class_scope:com.chuangqi.grpc.api.RPCDateResponseList)
  private static final RPCDateResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RPCDateResponseList();
  }

  public static RPCDateResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPCDateResponseList>
      PARSER = new com.google.protobuf.AbstractParser<RPCDateResponseList>() {
    public RPCDateResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RPCDateResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RPCDateResponseList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RPCDateResponseList> getParserForType() {
    return PARSER;
  }

  public RPCDateResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

