// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package org.learn.grpc.api;

public interface RPCDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuangqi.grpc.api.RPCDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serverDate = 1;</code>
   */
  String getServerDate();
  /**
   * <code>optional string serverDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
