// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package org.learn.grpc.api;

public interface RPCDateResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuangqi.grpc.api.RPCDateResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  java.util.List<RPCDateResponse>
      getRPCDateResponseList();
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  RPCDateResponse getRPCDateResponse(int index);
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  int getRPCDateResponseCount();
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  java.util.List<? extends RPCDateResponseOrBuilder>
      getRPCDateResponseOrBuilderList();
  /**
   * <code>repeated .com.chuangqi.grpc.api.RPCDateResponse rPCDateResponse = 1;</code>
   */
  RPCDateResponseOrBuilder getRPCDateResponseOrBuilder(
      int index);
}
