// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package org.learn.grpc.api;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuangqi.grpc.api.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userName = 1;</code>
   */
  String getUserName();
  /**
   * <code>optional string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
